use dagr::Dagr;

fn main() {
    let mut dagr = Dagr::new();
    dagr.add_nodes(
        vec![
            ("Auðumbla", "F"),
            ("Ymir", "M"),
            ("Þrúðgelmir", "M"),
            ("Bergelmir", "M"),
            ("Búri", "M"),
            ("Borr", "M"),
            ("Bölþorn", "M"),
            ("Bestla", "F"),
            ("Odin", "M"),
            ("Vili", "M"),
            ("Vé", "M"),
            ("Hœnir", "M"),
            ("Fjörgynn", "M"),
            ("Frigg", "F"),
            ("Annar", "M"),
            ("Jörð", "F"),
            ("Nepr", "M"),
            ("Gríðr", "F"),
            ("Forseti", "M"),
            ("Rindr", "F"),
            ("Dellingr", "M"),
            ("Nótt", "F"),
            ("Nanna", "F"),
            ("Baldr", "M"),
            ("Höðr", "M"),
            ("Hermóðr", "M"),
            ("Bragi", "M"),
            ("Iðunn", "F"),
            ("Víðarr", "M"),
            ("Váli", "M"),
            ("Gefjon", "F"),
            ("Ullr", "M"),
            ("Týr", "M"),
            ("Dagr", "M"),
            ("Thor", "M"),
            ("Sif", "F"),
            ("Járnsaxa", "F"),
            ("Nörfi", "M"),
            ("Móði", "M"),
            ("Þrúðr", "F"),
            ("Magni", "M"),
            ("Ægir", "M"),
            ("Rán", "F"),
            ("Nine sisters", "F"),
            ("Heimdallr", "M"),
        ],
        "Aesir",
    );

    dagr.add_nodes(
        vec![
            ("Alvaldi", "M"),
            ("Þjazi", "M"),
            ("Iði", "M"),
            ("Gangr", "M"),
            ("Fárbauti", "M"),
            ("Nál", "F"),
            ("Gymir", "M"),
            ("Aurboða", "F"),
            ("Njörðr", "F"),
            ("Skaði", "F"),
            ("Sigyn", "F"),
            ("Loki", "M"),
            ("Angrboða", "F"),
            ("Býleistr", "M"),
            ("Helblindi", "M"),
            ("Beli", "M"),
            ("Gerðr", "F"),
            ("Freyr", "M"),
            ("Freyja", "F"),
            ("Óðr", "M"),
            ("Vali", "M"),
            ("Narfi", "M"),
            ("Hyrrokkin", "F"),
            ("Fenrir", "M"),
            ("Jörmungandr", "M"),
            ("Hel", "F"),
            ("Fjölnir", "M"),
            ("Hnoss", "F"),
            ("Gersemi", "F"),
            ("Hati Hróðvitnisson", "M"),
            ("Sköll", "M"),
            ("Mánagarmr", "M"),
        ],
        "Vanir",
    );

    let relationships = vec![
        ("Ymir", "Þrúðgelmir"),
        ("Þrúðgelmir", "Bergelmir"),
        ("Bergelmir", "Bölþorn"),
        ("Bölþorn", "Bestla"),
        ("Bestla", "Odin"),
        ("Bestla", "Vili"),
        ("Bestla", "Vé"),
        ("Auðumbla", "Búri"),
        ("Búri", "Borr"),
        ("Borr", "Odin"),
        ("Borr", "Vili"),
        ("Borr", "Vé"),
        ("Ægir", "Nine sisters"),
        ("Rán", "Nine sisters"),
        ("Nine sisters", "Heimdallr"),
        ("Fjörgynn", "Frigg"),
        ("Frigg", "Baldr"),
        ("Odin", "Baldr"),
        ("Nepr", "Nanna"),
        ("Nanna", "Forseti"),
        ("Baldr", "Forseti"),
        ("Nörfi", "Nótt"),
        ("Nótt", "Dagr"),
        ("Nótt", "Jörð"),
        ("Annar", "Jörð"),
        ("Jörð", "Thor"),
        ("Odin", "Thor"),
        ("Thor", "Móði"),
        ("Thor", "Þrúðr"),
        ("Sif", "Móði"),
        ("Sif", "Þrúðr"),
        ("Thor", "Magni"),
        ("Járnsaxa", "Magni"),
    ];

    dagr.add_edge(8, 34, "parent");
    println!("{:?}", dagr);
}
